-- ENVIRONMENT: production
-- This file is auto-generated by the database migration tool.
-- postgresql://neondb_owner:npg_zevNYGH2Fk5W@ep-curly-dust-ae3jsfwm-pooler.c-2.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require

CREATE TABLE "users" (
"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "users_id_seq"),
"firstname" varchar(255),
"lastname" varchar(255),
"email" varchar(255) UNIQUE,
"mobile" varchar(255) UNIQUE,

"created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
"updated_at" timestamp DEFAULT CURRENT_TIMESTAMP,
"deleted_at" timestamp
);

"password" varchar(255),

INSERT INTO table_name (column1, column2, ...)
VALUES (value1, value2, ...);

UPDATE table_name
SET column1 = value1, column2 = value2, ...
WHERE condition;

DELETE FROM table_name
WHERE condition;

SELECT column1, column2, ...
FROM table_name
WHERE condition;

SELECT * FROM table_name;

INSERT INTO users (firstname, lastname, email, mobile)
VALUES ('bevan', 'Paulse', 'bevanpaulse@gmail.com', '0796968869');
-- This file is auto-generated by the database migration tool.
-- Do not edit this file manually.
